[workspace]
members = [
    "nova-core",
    "nova-adb", 
    "nova-mtp",
    "nova-backup",
    "nova-formats",
    "nova-cli",
    # "nova-ui", # Commented out due to system dependencies not available in CI
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["linuxiano85"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.77"
homepage = "https://github.com/linuxiano85/NovaPcSuite"
repository = "https://github.com/linuxiano85/NovaPcSuite"

[workspace.dependencies]
# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Async runtime
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Filesystem and paths
directories = "5.0"
dirs = "5.0"
tree_magic_mini = "3.0"

# Crypto
sha2 = "0.10"

# CLI
clap = { version = "4.0", features = ["derive"] }

# Async traits
async-trait = "0.1"

# Internal crates
nova-core = { path = "nova-core" }
nova-adb = { path = "nova-adb" }
nova-mtp = { path = "nova-mtp" }
nova-backup = { path = "nova-backup" }
nova-formats = { path = "nova-formats" }

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1