[workspace]
resolver = "2"
members = [
    "nova-core",
    "nova-plugin-api", 
    "nova-ui",
    "plugins/example-plugin"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["NovaPcSuite Contributors"]
repository = "https://github.com/linuxiano85/NovaPcSuite"

[workspace.dependencies]
# Core dependencies
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
semver = { version = "1.0", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# UI dependencies
eframe = "0.27"
egui = "0.27"

# Testing
rstest = "0.18"
tempfile = "3.8"